// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketFlow.Infrastructure.Persistence;

#nullable disable

namespace TicketFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420183654_AddUserIdToAuditLog")]
    partial class AddUserIdToAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 10, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Concierto de Rock Universitario",
                            Status = "Active",
                            Venue = "Estadio UNAJ"
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f2cece7-ea14-4604-ac7b-e188acb29941"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4e232ee0-e6a5-4fc9-a552-82e78ec64832"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5ec30a24-f4c6-4f34-a6b4-55a8e3d84660"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("cce9c553-d9d2-4e40-b224-cd086875b99f"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("23754202-0c08-4737-a07c-7c5b3e5210b7"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b61c2bfe-8d8f-4202-81c1-aa5ead3aceea"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6406d31f-4383-41f4-890c-d693aad86b59"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("82576377-b488-469b-8fbf-c665a31147e6"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9c3da1fc-c87d-4745-a5db-5f3327615183"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c1455283-cede-48a8-a92e-2ac112257b62"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("06838df7-113b-40d7-9527-ab5ee7e611e8"),
                            RowIdentifier = "A",
                            SeatNumber = 11,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("531ca843-da8a-499e-b74b-acd3a08d8841"),
                            RowIdentifier = "A",
                            SeatNumber = 12,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("eb3b7091-aa6d-4d20-8c8d-fe645059c977"),
                            RowIdentifier = "A",
                            SeatNumber = 13,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("49ba7bd5-cca6-4745-825b-37ed2f34c9f9"),
                            RowIdentifier = "A",
                            SeatNumber = 14,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f3005819-7342-49bf-a08e-d007b72bdcc3"),
                            RowIdentifier = "A",
                            SeatNumber = 15,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ef815079-bdc6-4fc3-a01c-c2a27c51752a"),
                            RowIdentifier = "A",
                            SeatNumber = 16,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("90f4e362-b19f-43ee-bde2-8f5adcccfe8b"),
                            RowIdentifier = "A",
                            SeatNumber = 17,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c2991480-1049-4d22-b467-a3b2e953e715"),
                            RowIdentifier = "A",
                            SeatNumber = 18,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("50255234-e469-4bef-aaec-de64c904fdea"),
                            RowIdentifier = "A",
                            SeatNumber = 19,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6ff06628-ff18-4fab-9215-d9806d4d71d7"),
                            RowIdentifier = "A",
                            SeatNumber = 20,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("1b48e9ec-51ac-43ea-9a86-61bdfe9934c7"),
                            RowIdentifier = "A",
                            SeatNumber = 21,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4ad45a40-ce20-43b8-a5ab-939b47b28bda"),
                            RowIdentifier = "A",
                            SeatNumber = 22,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0f578a36-d0e7-45a2-8036-9029c30945ac"),
                            RowIdentifier = "A",
                            SeatNumber = 23,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("46b10d2a-67aa-4da5-9b5b-f374585a38c1"),
                            RowIdentifier = "A",
                            SeatNumber = 24,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b385996f-f945-4554-ac41-10a9ee81697b"),
                            RowIdentifier = "A",
                            SeatNumber = 25,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0701d2eb-7792-4c6f-b713-485c1a422626"),
                            RowIdentifier = "A",
                            SeatNumber = 26,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ae3fa21c-c78f-4b16-a713-e9ab23c0ce81"),
                            RowIdentifier = "A",
                            SeatNumber = 27,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ed605ddd-bfd6-467f-ae92-7fc6cfc54e98"),
                            RowIdentifier = "A",
                            SeatNumber = 28,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3218b74d-b7e4-4f74-b995-30df2385620d"),
                            RowIdentifier = "A",
                            SeatNumber = 29,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5dd5490e-0b63-4c4e-be97-637fb8e502ab"),
                            RowIdentifier = "A",
                            SeatNumber = 30,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("da4d834c-8218-48ed-b802-fd19ad46c17c"),
                            RowIdentifier = "A",
                            SeatNumber = 31,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d86678ae-6fa8-4a8c-8c04-1664a2ae9647"),
                            RowIdentifier = "A",
                            SeatNumber = 32,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("95abbb9d-db10-4c58-9610-dc85111c9af5"),
                            RowIdentifier = "A",
                            SeatNumber = 33,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("29114ac1-6b5b-45f5-a1cd-5d01ecba295d"),
                            RowIdentifier = "A",
                            SeatNumber = 34,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ad978ff2-37ae-42b4-9c5b-413841438aa0"),
                            RowIdentifier = "A",
                            SeatNumber = 35,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("80d90e68-fe42-4f24-b30c-93ee07fa772d"),
                            RowIdentifier = "A",
                            SeatNumber = 36,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("620439ae-4118-4074-aa85-0c9cd8df11c3"),
                            RowIdentifier = "A",
                            SeatNumber = 37,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c5528d50-3625-4454-b5f6-952286446592"),
                            RowIdentifier = "A",
                            SeatNumber = 38,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b9907da4-e4bb-4f74-9e78-cf44c800b83b"),
                            RowIdentifier = "A",
                            SeatNumber = 39,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("43e3abe6-6616-4507-bb88-f2b1e443382f"),
                            RowIdentifier = "A",
                            SeatNumber = 40,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("777e36c0-c391-415b-9148-f9e8ff917042"),
                            RowIdentifier = "A",
                            SeatNumber = 41,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("614617e5-9a92-470d-9aea-d475c1ad00fb"),
                            RowIdentifier = "A",
                            SeatNumber = 42,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("860d2bc2-d267-4c58-a321-2b1e7bd0de22"),
                            RowIdentifier = "A",
                            SeatNumber = 43,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a41b471c-02cf-4552-9358-4247bce3fecb"),
                            RowIdentifier = "A",
                            SeatNumber = 44,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d24790db-48ca-40d5-898d-28331713560e"),
                            RowIdentifier = "A",
                            SeatNumber = 45,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3ee29462-a6f5-4ab5-84b5-726e88771220"),
                            RowIdentifier = "A",
                            SeatNumber = 46,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5c482d77-456f-4c6e-bb75-3fc512c67532"),
                            RowIdentifier = "A",
                            SeatNumber = 47,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f474a6f3-5310-478c-b7fa-cfa6e40502e9"),
                            RowIdentifier = "A",
                            SeatNumber = 48,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9bf1d709-3ab2-45aa-8614-f1aee770f835"),
                            RowIdentifier = "A",
                            SeatNumber = 49,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7fa8521a-98e2-4d38-916b-d3e807ed7ea7"),
                            RowIdentifier = "A",
                            SeatNumber = 50,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("70c8ea43-0359-42d6-9d60-3e1e94e835b8"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a99884eb-889c-44fd-bfa0-f2dfc77e477b"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e1260e44-842c-4dd3-9640-43b08252f018"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ca1562b3-2494-4960-82a3-e84a0ad8f3bc"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3668e3a3-d6b8-4987-b5be-002cf44cc8e7"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("034e23db-a732-422f-802b-7259933ad7ea"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e48b6149-f9e9-4931-88bc-c0f8621bcbb3"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("08b7d80f-b451-494e-b684-1d76b70706da"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("07a18e45-4197-4700-aa5c-8ab5b12959c8"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("509a1453-6445-45f8-82eb-38d53b23b09c"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ca43deaa-84e4-47cd-9d32-49d5b4a0c5ec"),
                            RowIdentifier = "B",
                            SeatNumber = 11,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("07099f0c-d072-4ac4-9349-0c3ac7f50ae5"),
                            RowIdentifier = "B",
                            SeatNumber = 12,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8ff99d67-0014-46b5-a84d-2e44a671814c"),
                            RowIdentifier = "B",
                            SeatNumber = 13,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9f4d3fd3-23dd-464c-8a4c-2c8cfe4a2f56"),
                            RowIdentifier = "B",
                            SeatNumber = 14,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8e2cfb12-95cb-4d2e-b4bc-7f550d121742"),
                            RowIdentifier = "B",
                            SeatNumber = 15,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d7c19a31-bc7c-4c8c-9ca0-d79eeaa3d882"),
                            RowIdentifier = "B",
                            SeatNumber = 16,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("969d627f-0a73-40a8-9f08-57fbfe35966c"),
                            RowIdentifier = "B",
                            SeatNumber = 17,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("322a32ff-0bff-469b-8463-de4c085cae7b"),
                            RowIdentifier = "B",
                            SeatNumber = 18,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b80f4cb5-8e32-4ea9-977f-894a69918c37"),
                            RowIdentifier = "B",
                            SeatNumber = 19,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c750fa4a-edb3-4828-9d93-408f4c354e5e"),
                            RowIdentifier = "B",
                            SeatNumber = 20,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0fba01f6-65e9-475f-8af8-d89f5323ff3f"),
                            RowIdentifier = "B",
                            SeatNumber = 21,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f77e144c-b524-42db-af2f-59638a6696a7"),
                            RowIdentifier = "B",
                            SeatNumber = 22,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c003ff58-633a-4ca5-a9ad-8a82a2f84da1"),
                            RowIdentifier = "B",
                            SeatNumber = 23,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b21bff10-d1e0-4c70-819f-1b7b7306fbb7"),
                            RowIdentifier = "B",
                            SeatNumber = 24,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3777f8bf-ccde-4072-bd85-ca2c796cd732"),
                            RowIdentifier = "B",
                            SeatNumber = 25,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("fdc5ba0c-741f-44d4-bc62-ca662d990405"),
                            RowIdentifier = "B",
                            SeatNumber = 26,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("575a78b6-bf6e-471d-8969-4f28ba9ec4a2"),
                            RowIdentifier = "B",
                            SeatNumber = 27,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a2f3271f-b725-44c9-baa6-7901cd7c0f42"),
                            RowIdentifier = "B",
                            SeatNumber = 28,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("cb64e8c6-b8a3-4876-bb83-d96f2d4b66fd"),
                            RowIdentifier = "B",
                            SeatNumber = 29,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f8d20daa-eb32-4131-ae4d-628581f19995"),
                            RowIdentifier = "B",
                            SeatNumber = 30,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6f9c8f34-e100-4c4e-b116-8760f44b0563"),
                            RowIdentifier = "B",
                            SeatNumber = 31,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8ffc6dc5-dde5-4094-9f27-89bddf817f37"),
                            RowIdentifier = "B",
                            SeatNumber = 32,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f3b58165-051b-4c95-a0ab-b87398c823f1"),
                            RowIdentifier = "B",
                            SeatNumber = 33,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("85647410-379f-49c8-ad50-4a4d083d2e6d"),
                            RowIdentifier = "B",
                            SeatNumber = 34,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("47c29f29-b8f8-47e5-ace2-28a633dbd771"),
                            RowIdentifier = "B",
                            SeatNumber = 35,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("59ab5e7b-5066-4a97-a579-29df0f62b707"),
                            RowIdentifier = "B",
                            SeatNumber = 36,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ad41d481-20a6-4a78-ace0-3ee69a45f746"),
                            RowIdentifier = "B",
                            SeatNumber = 37,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ea33fbb9-856c-4211-9111-d889106478a9"),
                            RowIdentifier = "B",
                            SeatNumber = 38,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6bda3e93-77d0-4caa-a4d1-8ea9e4978fec"),
                            RowIdentifier = "B",
                            SeatNumber = 39,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f96b813e-f4e2-4978-b5dd-53b435529ba8"),
                            RowIdentifier = "B",
                            SeatNumber = 40,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9041d667-7304-4497-8aaf-cda778120937"),
                            RowIdentifier = "B",
                            SeatNumber = 41,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("908d00ee-b09f-41f2-9718-6c87b8714b59"),
                            RowIdentifier = "B",
                            SeatNumber = 42,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("216b2a97-3c87-4252-9ba2-25ad978bae17"),
                            RowIdentifier = "B",
                            SeatNumber = 43,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("045393af-57c3-4770-b56d-9c9fb204b9fc"),
                            RowIdentifier = "B",
                            SeatNumber = 44,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("866c3ee2-6164-4e77-868d-b24c28b38869"),
                            RowIdentifier = "B",
                            SeatNumber = 45,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8c5bfb4e-fa78-4817-888f-715ef3fbcaf6"),
                            RowIdentifier = "B",
                            SeatNumber = 46,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("bfb1ceae-beec-4e11-9041-4dd0a292b9aa"),
                            RowIdentifier = "B",
                            SeatNumber = 47,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c61a0f57-6c5c-418e-9ce8-a4946fba28b2"),
                            RowIdentifier = "B",
                            SeatNumber = 48,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("773829ce-02d8-440b-98cc-21f9474cdbee"),
                            RowIdentifier = "B",
                            SeatNumber = 49,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f612f4ce-2b14-4a7f-991c-4d2cb71c9ad3"),
                            RowIdentifier = "B",
                            SeatNumber = 50,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Sectors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "VIP",
                            Price = 15000.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "General",
                            Price = 5000.00m
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketFlow.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Seat", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Sector", null)
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Event", null)
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Event", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
