// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketFlow.Infrastructure.Persistence;

#nullable disable

namespace TicketFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418214557_AddSectorsSeatsAndSeeding")]
    partial class AddSectorsSeatsAndSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketFlow.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 10, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Concierto de Rock Universitario",
                            Status = "Active",
                            Venue = "Estadio UNAJ"
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("463904f5-adaa-4d50-8213-74cb979a14e0"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f9571c5f-db8a-49b8-bfbb-1729196982d6"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("50ed3c68-6fc9-471c-b41a-24e5b53b5a38"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("85aca70e-8fc2-400f-ab9e-1aa35aa5dc10"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("40a32b93-dbb0-40c5-ab30-574131d62cfe"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("03b68653-6e92-45b7-962d-9e9cf3344138"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ce161f24-6e44-4ce1-9e6d-55a64ad026fc"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f1f5e8e1-e58f-416f-88ee-ac15fd1f7f5b"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("bded897b-9757-4fdb-a8ba-30c2d2b0c8a7"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("828474c8-f596-44e0-8352-7165185f1875"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3619b6cc-e227-4fc8-9e9e-a85cd6f7e743"),
                            RowIdentifier = "A",
                            SeatNumber = 11,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6bbefeef-6c05-4d90-aa94-76d336698ae2"),
                            RowIdentifier = "A",
                            SeatNumber = 12,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("fa15b0cb-7fa8-4744-9a51-2cf936c156fa"),
                            RowIdentifier = "A",
                            SeatNumber = 13,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6022b1e7-81ee-4925-a03c-8398fae73d26"),
                            RowIdentifier = "A",
                            SeatNumber = 14,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("926dc2ee-6fb5-4928-97b0-5c2d0452e3c7"),
                            RowIdentifier = "A",
                            SeatNumber = 15,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5ce8ffa4-92ef-4b36-bbdd-b9a3e16e928a"),
                            RowIdentifier = "A",
                            SeatNumber = 16,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7058f2f3-4674-4bb7-83d1-15f44156a12b"),
                            RowIdentifier = "A",
                            SeatNumber = 17,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("92ecbd2a-4f7e-4585-81f1-25b371ecec5b"),
                            RowIdentifier = "A",
                            SeatNumber = 18,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("dbdedba5-57e8-4a7f-86c3-52704b381d0c"),
                            RowIdentifier = "A",
                            SeatNumber = 19,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("094883d5-f3ad-4d69-92d6-13f151d0f9b5"),
                            RowIdentifier = "A",
                            SeatNumber = 20,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("fbb7be59-a921-458f-ba94-d3a31185c8f7"),
                            RowIdentifier = "A",
                            SeatNumber = 21,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("adbd34df-6ef3-428c-bcb3-6ed810b31297"),
                            RowIdentifier = "A",
                            SeatNumber = 22,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4474655f-23f0-4566-b2d6-5cd8d05fe2a7"),
                            RowIdentifier = "A",
                            SeatNumber = 23,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3514f7dc-e1a4-4380-a052-662389cc0a0b"),
                            RowIdentifier = "A",
                            SeatNumber = 24,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("308cc514-888b-4b05-abe3-ef6135470920"),
                            RowIdentifier = "A",
                            SeatNumber = 25,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f1dd2067-1f83-4031-9002-11ae132a8c9a"),
                            RowIdentifier = "A",
                            SeatNumber = 26,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b64e2eee-080f-4a1b-9fe1-08e12dd61e3c"),
                            RowIdentifier = "A",
                            SeatNumber = 27,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7f52a596-78c1-4645-8ccc-07cf8c54b56f"),
                            RowIdentifier = "A",
                            SeatNumber = 28,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("baaedf43-eead-453c-95b1-bae608c92ab8"),
                            RowIdentifier = "A",
                            SeatNumber = 29,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("934ea849-b7eb-407e-a863-ec1709a02a4c"),
                            RowIdentifier = "A",
                            SeatNumber = 30,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("065e2910-df2a-4bf6-bbf6-b7c0c73ca130"),
                            RowIdentifier = "A",
                            SeatNumber = 31,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("deb8f823-7118-44f3-bfba-71a61b0579fa"),
                            RowIdentifier = "A",
                            SeatNumber = 32,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("612dc299-1973-450b-bced-7c43fcbcb1d0"),
                            RowIdentifier = "A",
                            SeatNumber = 33,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("55e9a790-8cd2-4fea-9f7e-9fa18c4b7680"),
                            RowIdentifier = "A",
                            SeatNumber = 34,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9f668963-b121-47c9-9ad7-146700861b0a"),
                            RowIdentifier = "A",
                            SeatNumber = 35,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("42562e91-88f0-48aa-b352-b453d93151a4"),
                            RowIdentifier = "A",
                            SeatNumber = 36,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a80ee77f-fa62-4d87-8b46-3c6cc96cf575"),
                            RowIdentifier = "A",
                            SeatNumber = 37,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("2ccd03de-aed6-4b31-9663-7e9543c6a18d"),
                            RowIdentifier = "A",
                            SeatNumber = 38,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b0791afd-5113-4cc5-a7a0-ae4c7db691c3"),
                            RowIdentifier = "A",
                            SeatNumber = 39,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("53017212-3de7-4f79-a8aa-688069445f8d"),
                            RowIdentifier = "A",
                            SeatNumber = 40,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("63ea2c22-4177-4d95-a404-2148b97c8753"),
                            RowIdentifier = "A",
                            SeatNumber = 41,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("25adfae1-e0fe-4039-a6d2-91a4aabcfcac"),
                            RowIdentifier = "A",
                            SeatNumber = 42,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a77dc70b-0643-4b7c-9da4-53b858e6334b"),
                            RowIdentifier = "A",
                            SeatNumber = 43,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a96e0566-20ef-4a54-b98d-4f54dadf1bcd"),
                            RowIdentifier = "A",
                            SeatNumber = 44,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("73cc61a7-8b8d-4090-b164-18de49408e67"),
                            RowIdentifier = "A",
                            SeatNumber = 45,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("95db05fe-67d6-430c-a6dc-fc9916f4d55c"),
                            RowIdentifier = "A",
                            SeatNumber = 46,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4d3b4be1-28d5-48dc-a4f0-7e35f426547b"),
                            RowIdentifier = "A",
                            SeatNumber = 47,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c4b133e9-4eec-4e9d-ae5f-d05c30614243"),
                            RowIdentifier = "A",
                            SeatNumber = 48,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("2541b945-8808-4693-9f04-d29c0d147b52"),
                            RowIdentifier = "A",
                            SeatNumber = 49,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ae508171-f18b-4e20-8452-efca3c6b36f8"),
                            RowIdentifier = "A",
                            SeatNumber = 50,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("433789e6-e19e-452b-9b9f-9ae9ed37a509"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("cb40ef1a-f9a8-4e07-ad1b-e74540c876ac"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("50a97312-da5b-4bfd-bf9f-a820809bfd60"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8a9b040e-8128-4334-b918-f0eed328704e"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("2755b48a-0f09-434e-9b8c-9946a9fe60d4"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("18e2cacf-83cb-45e3-991e-8b185ce924c3"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f514adc9-3d76-4b79-8e62-4906e32226db"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8709ad40-3295-4418-9071-99264202cdc0"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3d8fed55-468b-49af-85b6-425390e5c38b"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("687b142c-8f4b-4f39-92ba-a2c9617432b9"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("206732de-a035-4808-b5ca-8dfd511b647d"),
                            RowIdentifier = "B",
                            SeatNumber = 11,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("56e5b24b-d76e-4c05-8fc4-a900cee47d90"),
                            RowIdentifier = "B",
                            SeatNumber = 12,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3f558448-468d-4853-a26b-3f6c30d458a3"),
                            RowIdentifier = "B",
                            SeatNumber = 13,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("fb16c8d3-7ee2-4397-95bc-3d9d1d441027"),
                            RowIdentifier = "B",
                            SeatNumber = 14,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("798fa49d-0fb2-4675-be86-75fa1c274a80"),
                            RowIdentifier = "B",
                            SeatNumber = 15,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f25a0709-32da-45f8-9275-da381d05b8b9"),
                            RowIdentifier = "B",
                            SeatNumber = 16,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("136037de-cd83-43d6-8d63-fe39a73d9d3b"),
                            RowIdentifier = "B",
                            SeatNumber = 17,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5badab93-c929-45fe-a4bb-8d23dfb451c5"),
                            RowIdentifier = "B",
                            SeatNumber = 18,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("58e7b881-96f8-4b39-bfb4-f222976a61f9"),
                            RowIdentifier = "B",
                            SeatNumber = 19,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("30b7b28e-6812-4949-badf-199b00f147e8"),
                            RowIdentifier = "B",
                            SeatNumber = 20,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0f8a52d1-cb0b-4966-8d2a-c94be4f55b7e"),
                            RowIdentifier = "B",
                            SeatNumber = 21,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e1826b78-f963-4705-a153-a238acd09ab7"),
                            RowIdentifier = "B",
                            SeatNumber = 22,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0e8a37c5-c9d7-4686-8631-b75ecdba5a02"),
                            RowIdentifier = "B",
                            SeatNumber = 23,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3e63d703-298b-4a2e-9e3e-5a1baa7bff68"),
                            RowIdentifier = "B",
                            SeatNumber = 24,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("145be9b8-43a3-4085-8b4f-effb53a3503b"),
                            RowIdentifier = "B",
                            SeatNumber = 25,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9a52cb9d-cc94-4818-94d3-a384b0e9230f"),
                            RowIdentifier = "B",
                            SeatNumber = 26,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9e029466-6109-4080-9505-08b747ff02a6"),
                            RowIdentifier = "B",
                            SeatNumber = 27,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("92ac7f7e-c296-47c8-876d-63781046d267"),
                            RowIdentifier = "B",
                            SeatNumber = 28,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("26850e48-77b0-48c4-966e-7a464bd58fc0"),
                            RowIdentifier = "B",
                            SeatNumber = 29,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("eac573d1-7eea-4335-b64d-7696d31fe240"),
                            RowIdentifier = "B",
                            SeatNumber = 30,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4065c6cd-f6a4-451d-9e93-b7f7789adc60"),
                            RowIdentifier = "B",
                            SeatNumber = 31,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4103b6df-a6b1-4a31-85d3-4815de3d2bb4"),
                            RowIdentifier = "B",
                            SeatNumber = 32,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("bdd41749-a153-4809-975f-ca6f6c886413"),
                            RowIdentifier = "B",
                            SeatNumber = 33,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("cd55baee-5b68-4166-92ae-b29fd957a10b"),
                            RowIdentifier = "B",
                            SeatNumber = 34,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("bedeadca-2f6a-4814-b456-4af4be061c79"),
                            RowIdentifier = "B",
                            SeatNumber = 35,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("fa4388cb-dcdc-45ec-b9cf-7cfc47f216c5"),
                            RowIdentifier = "B",
                            SeatNumber = 36,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("250d4f35-8929-4dbe-bcbf-c78de7daf9bc"),
                            RowIdentifier = "B",
                            SeatNumber = 37,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f75385c7-a671-4a6e-896f-0e810955b3ae"),
                            RowIdentifier = "B",
                            SeatNumber = 38,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6622cda5-18a9-4966-84fa-84e99788d6d7"),
                            RowIdentifier = "B",
                            SeatNumber = 39,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("683cc6d3-faa4-4134-873e-f9ab0842fb8a"),
                            RowIdentifier = "B",
                            SeatNumber = 40,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("703d1f46-b591-4250-91f3-d78f3dc1c45d"),
                            RowIdentifier = "B",
                            SeatNumber = 41,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5acfe074-f131-4f9d-a229-4cbb05408f34"),
                            RowIdentifier = "B",
                            SeatNumber = 42,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("aebc0cb3-3386-4da2-9e1a-c068b8dc481a"),
                            RowIdentifier = "B",
                            SeatNumber = 43,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b7e3643d-6d28-4ec0-a25b-79fe953bab88"),
                            RowIdentifier = "B",
                            SeatNumber = 44,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("025643d9-6fd1-4502-8621-27c33a20b942"),
                            RowIdentifier = "B",
                            SeatNumber = 45,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0202a046-5b97-4da8-8b0c-cdda5183c8eb"),
                            RowIdentifier = "B",
                            SeatNumber = 46,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("03292de0-83f2-4b9d-ab37-cddd0e6e1c3d"),
                            RowIdentifier = "B",
                            SeatNumber = 47,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("77f93cca-b1fd-4fcd-8af1-b3749bd38b2d"),
                            RowIdentifier = "B",
                            SeatNumber = 48,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3669b857-6007-4612-a44a-2c364c412a49"),
                            RowIdentifier = "B",
                            SeatNumber = 49,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f13700fc-f909-47af-9a94-e1be4f4cf056"),
                            RowIdentifier = "B",
                            SeatNumber = 50,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Sectors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "VIP",
                            Price = 15000.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "General",
                            Price = 5000.00m
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Seat", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Sector", null)
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Event", null)
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Event", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
