// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketFlow.Infrastructure.Persistence;

#nullable disable

namespace TicketFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508181320_AddAuthFieldsToUser")]
    partial class AddAuthFieldsToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 10, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Concierto de Rock Universitario",
                            Status = "Active",
                            Venue = "Estadio UNAJ"
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("12fab705-7354-4883-8b61-57b10ef05037"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("79f56afa-e1a8-4b0d-b391-fa2b3460bad5"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b39a8227-6c1f-4393-a5e4-16c6b825e89d"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d12f6eb9-29ec-4deb-81d0-7d78fb644fb1"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("115e1236-8a91-467b-a677-c864f30697a3"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("1768294a-fa25-4e90-838c-6b1e0b6e1733"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ac67a541-d387-4f8a-91c0-6d846ac9632b"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d2a8531f-af30-4c37-8f82-249844b41010"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("1954284f-1db1-4fdc-902a-998a6b6740b5"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e8c97102-6289-4d65-834b-275d37254e73"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b7caace8-6352-4a6a-9114-118c7a487179"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5b2153a5-23a3-41e8-ad8e-e41ece088f5f"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("dd83a7cb-ab1c-49ad-ae08-885c4def434c"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e8768449-6ef1-420a-b533-53b3e4685c54"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("512cf0b7-38a9-4221-8ffe-f4535c2bb746"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f7ad2383-6dc8-45e6-bce0-ea6a6f31d623"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("981c064f-ea35-4730-8f0f-e4da5900fa8b"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7dd9f62d-00f9-4591-b533-63662d190ab1"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b791c35a-1137-43dd-8c99-2a8bda0eae17"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("2c32e646-9acd-4475-856d-21d35a084cdf"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a2f21b5c-21ee-4a04-b6fe-cb429f406da3"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("16739d69-61fc-46de-87eb-c43408c04d21"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("2c76bc45-d0fa-4314-9020-225c5982c1d9"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("76eda118-7458-4185-a7a4-b81ba8d12b5b"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ac723e50-bb10-49dd-b1e7-6ab7e5eaf240"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("def5f354-55a2-42b9-aa59-2bbcc9d9551d"),
                            RowIdentifier = "C",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4fe54889-499b-484a-8cf7-a2fbc8aebe58"),
                            RowIdentifier = "C",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ae1460bd-8e8c-414b-a38d-0429e2450bde"),
                            RowIdentifier = "C",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9fd0611c-1be9-42f1-b626-44bd830d54fd"),
                            RowIdentifier = "C",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b61cbb86-4323-4763-a825-78680c75f957"),
                            RowIdentifier = "C",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6ff1fc92-5088-46e7-8dbb-d44589710954"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0d0fe4b8-2767-4003-984e-5698e9824a4e"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0f3e71f9-ccfd-48ad-b9ca-938f1957e6c1"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("46a0efe1-c990-4049-917e-417afcfba1b5"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("46936849-f6ab-4081-a3a6-297fc69fa1ff"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f041fda6-a664-481b-9728-631f103093fe"),
                            RowIdentifier = "D",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("deb8782d-6a7b-4633-99c0-00c890956cd4"),
                            RowIdentifier = "D",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("bb74ad9f-c66e-4272-8f98-a24dc2323bae"),
                            RowIdentifier = "D",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("251aad74-6b42-4b09-a5e3-de87901a7ed0"),
                            RowIdentifier = "D",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("74dfa587-0e6e-43f4-85bb-956839267306"),
                            RowIdentifier = "D",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("74d9851e-cbce-4934-9d84-a8c7f400bfd9"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("03fb8b35-4810-41d0-aa5a-1a2ff00c0b88"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("fc28faec-8844-45d0-956a-0922e91445f5"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e941631c-bd52-4161-924e-a55eb7df0d8c"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("644dcf95-f5a3-4794-9f87-8a445b0a75cf"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a6e8b0b8-ca2a-464a-8977-3353549101e9"),
                            RowIdentifier = "E",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e2005d-a189-4b20-a06f-dc6c77f40b11"),
                            RowIdentifier = "E",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("fcfa7368-d87d-4df0-a3de-cc38ecd2e92c"),
                            RowIdentifier = "E",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("16234610-2f9f-474e-bf2e-d3915fc65655"),
                            RowIdentifier = "E",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3cca9d63-efa6-4a99-9c51-b463ade623bf"),
                            RowIdentifier = "E",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4fc62670-0b24-4054-896a-c7225f17cbb0"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("da49e168-b694-40af-a676-32af3441d422"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("202bca41-f7a7-41f4-a388-d8395ba2a3db"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("13af99a3-71e6-4ae5-a5f5-d3ddf814a0a0"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c7575053-d4fd-4360-9a3a-3c4b8a02478a"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c07d37f8-54ca-4010-aaa7-6a9956925c9c"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8b479e9e-a547-453c-9cc1-3460f94f594f"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("2c879a83-63ae-4ea4-8151-76298cef7350"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("573c4779-aa5a-46cc-9fff-0bb42b08fda0"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9fce73a4-ff7b-4dac-a66a-a1ce0f66f417"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("2a9f6894-9b3e-401c-9899-a67a64403360"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("51d934b8-57c0-41b0-8952-ec1da82cd1bc"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9cd4d0d0-f255-4da5-8df6-ba09ee24039b"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("1964258c-4b64-47bc-9bca-ee6afc6314f2"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("14581d5e-9428-4a8b-817a-2f261e202595"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("041bfd9c-eefb-4f2d-9ff1-8258d046d627"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("14daf5c3-1aba-49f7-9e09-4493015e725f"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b617fb0c-b757-4f07-8500-f8dfe0ccd9e0"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("2153a6ed-f968-451c-af23-b1205102454a"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0fb98f44-f2e0-446a-a076-e26e4dd6ef76"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8c7306af-fc43-4782-a4b6-648d92180efa"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("66eeb61b-8b0f-4800-a8d3-5fc9a519cb33"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("cf1bb88e-bfda-4783-aec2-a28e73eb3c8f"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("85cc404d-2bc5-493d-8fd4-d10955c2606e"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e95522a4-24d8-4b82-b844-1cbba3a76a83"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("15f6bb01-aedf-486f-bd5d-6f7dc39a61d4"),
                            RowIdentifier = "C",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("15cef4db-fc3b-4733-a6aa-a9a84bdc244f"),
                            RowIdentifier = "C",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("231bf464-b6b7-408b-90b7-fbc4b91883b8"),
                            RowIdentifier = "C",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("012fa838-7617-483e-a403-debd7f3b89be"),
                            RowIdentifier = "C",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("555bc595-669b-4829-b5e5-cee2a71f674e"),
                            RowIdentifier = "C",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("25c25e02-de6f-442f-80d6-37aa7f98ad9b"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3140f751-ebf2-4fb2-8316-6e3d11821dde"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("70a63ee8-861c-4b13-9cb3-92367c73e1bd"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7ea5f2d6-2f23-4cbb-bb69-05a27ee09fee"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d185c197-eae7-4dbf-a109-f970cd41acd6"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("344d0a26-a100-485f-91fe-47f0250f4e9e"),
                            RowIdentifier = "D",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a132eaa4-c5ea-438c-b8d7-b542514f8137"),
                            RowIdentifier = "D",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("1ac7719d-702b-442e-9751-7835794c84a8"),
                            RowIdentifier = "D",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("94088506-7fb2-4f57-9d03-78b73ba171aa"),
                            RowIdentifier = "D",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("31c05d70-192e-4b3c-b884-c3acf298ef5c"),
                            RowIdentifier = "D",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("12175de4-c59c-4504-a742-343df1768260"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a3f5ab4b-fe62-42a0-9ed2-1573a6bf0810"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("59032d96-1b20-4840-af03-419ebff903f0"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("df536c92-5c77-47af-a636-79d533c08986"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8b5b87f1-79e4-40f9-aa7c-898a0f1b8cde"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0e2b2d6c-47a3-495a-93cc-b979dedc4b5f"),
                            RowIdentifier = "E",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d475b647-d5b0-4d82-ae4a-6444e76dbcb3"),
                            RowIdentifier = "E",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("bdab22d9-01fc-4402-84bb-62089d142493"),
                            RowIdentifier = "E",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c7368db1-4c21-48fd-82ee-52283842de50"),
                            RowIdentifier = "E",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5d63c7a7-fe73-4ea7-82b7-cd16a3c45ce0"),
                            RowIdentifier = "E",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Sectors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "VIP",
                            Price = 15000.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "General",
                            Price = 5000.00m
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "agus@ticketflow.com",
                            Name = "Agustin",
                            PasswordHash = "123456",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ale@ticketflow.com",
                            Name = "Alejandro",
                            PasswordHash = "123456",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 1,
                            Email = "admin@ticketflow.com",
                            Name = "Admin General",
                            PasswordHash = "admin123",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketFlow.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Seat", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Sector", "Sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Event", "Event")
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Event", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
