// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketFlow.Infrastructure.Persistence;

#nullable disable

namespace TicketFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512203746_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 10, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Concierto de Rock Universitario",
                            Status = "Active",
                            Venue = "Estadio UNAJ"
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5686244a-0404-42c5-b3b4-a496a233d816"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5771de67-a4df-43f8-8164-6d9949368448"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6c9bd68d-bf08-4fcd-9196-b51d76e222b1"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("190a9d38-4fa5-4035-8d52-e12014b98b80"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("95e59c3b-fa0b-41b5-a10c-4f86fa9ed79b"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f6cc3f32-2573-4012-a4b6-aa061def206b"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d41b0f36-2871-4cf6-b4f9-d3147e8468ce"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("101e6b7e-473c-4b60-90f9-3d9439b478aa"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d8922f0c-b233-4804-bb01-99aa6f85bd37"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("df5cf9bb-e0bd-4c66-a969-c4e4ee2d2b6e"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("030373eb-8105-42a0-bfca-acdbb5657377"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("399863d6-1535-4982-b08b-1fad8f935ae4"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("acaeee57-18dc-42a0-af04-de1c763e3b82"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9b838391-28e1-48e9-83bd-de158be1ffd8"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0eafb96f-6a39-49ea-9daa-21fd3615e640"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d5d5de39-c3c2-4713-9fc2-dee3092f057f"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a8ff6acf-9c3d-4d42-b961-cccad8a615fd"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("19d9332e-5db7-4ff2-bbbf-a5f1754725ae"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3ba9ca45-5c69-4617-82f0-c4568c975111"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3b1f6b40-c0cd-4981-b634-76ec4eaab0f7"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0e7b8ff4-ee7a-40b8-9564-d0356c2af553"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d87f4f3d-ff49-4dd4-8933-f1161628886b"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6e21eda4-48e9-4b88-89cf-f9d82709fb56"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d58ef2bb-9b0f-4fd6-9798-d3f2a671ae83"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f2f1db88-20cd-4e72-ba38-33212da2f7a7"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("044a94df-94dc-4850-b3d5-540dc02bea6b"),
                            RowIdentifier = "C",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("fc36f2d3-b3cb-4f7b-815b-16ca23dbf0e9"),
                            RowIdentifier = "C",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("649db2ed-41ab-4560-9239-bd7ef90ce25d"),
                            RowIdentifier = "C",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d545db8a-8a2f-499c-9895-006e6b20c846"),
                            RowIdentifier = "C",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7c4c9248-18a7-4bdd-8116-fdf1847cf17f"),
                            RowIdentifier = "C",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("885c10c7-3b58-4558-a503-afaf47fe4a0c"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3b4e8d40-8a4c-4f52-8e83-b4d97bd5b110"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d71cac50-66bb-42d4-93dd-29bb565118fc"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("83e0f7ea-65eb-4c73-94da-f7ea1b0b67b0"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("fdeba8f8-324d-4ceb-a49d-1b22ba2a6e09"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a81850c8-9b01-4b6e-b7df-021aab2822e9"),
                            RowIdentifier = "D",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("735eb79a-bcf4-425c-a164-08c1488846bb"),
                            RowIdentifier = "D",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a0b079e9-bff7-4e76-b8fc-5f2e01e222f9"),
                            RowIdentifier = "D",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("cca19017-a35b-40dc-887a-5ced526b5b04"),
                            RowIdentifier = "D",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("71b99f17-6b25-4a20-8dbe-03003c5a5e7e"),
                            RowIdentifier = "D",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("43e879b9-0c5c-4391-9064-5c292f06bc7c"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c53e608b-4bd0-4b2b-948d-670b9b64bb98"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e4fd9858-b6d2-4f5b-818f-04cfd32e3688"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("21422f23-0713-4c5b-ae3c-5de3a8fee0e0"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4e6286ec-2ee7-4bc0-a192-7fd1e530b9ed"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("219b3879-39bd-4ee5-8dc5-81022770fb74"),
                            RowIdentifier = "E",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b22a6fff-9784-4a86-a60f-ae717f84e28f"),
                            RowIdentifier = "E",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5ba002b9-0493-47d1-bb60-4153e49c8dff"),
                            RowIdentifier = "E",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8e3de70f-fb64-4924-82e9-7e5e7719bcb7"),
                            RowIdentifier = "E",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("2c60745c-b1b3-4a87-903d-79041f19a8b2"),
                            RowIdentifier = "E",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("542446aa-0b2e-4106-be81-625740f22ba2"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("abda7ac4-0004-491c-9540-2153341fd238"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("1640aa7d-c342-4ba7-b8df-f840492344dd"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5d6bd76d-7dee-4686-914c-e83aa00f08cf"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4f5afd7f-5eb3-4b72-b24d-4dc51f574491"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0d409fc9-2d09-47ce-8b8e-b96e68f10fcd"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("36e560a0-70b3-4422-8616-9a695affb728"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a64dc812-a78d-43a3-b5f7-12dfd96157c7"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e1fa8d2f-8755-4407-b153-848bc2b9839d"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8771c9d3-381e-434c-a797-7e659671acce"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6759a651-9a19-4945-ab2e-7d2a811c4b82"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4c7625ec-1bf4-4f52-a659-bee9c537701f"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6c1fcb2f-5bb8-4204-9bdd-79b2fedf3ae2"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b0d60168-b8bd-4bfe-97fd-2b36995c9aee"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("80f5c295-5d9d-4429-bc60-c4ed216a1fb8"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("511c0425-d335-4ec4-892a-9dde1394c385"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("30f9f2ef-5be2-4a4f-b418-0c919db3e9ce"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e09ab150-1111-475f-b973-157f3650d7e2"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9e9f5008-581b-4d57-8649-c762c4a22a9b"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("29cfcef0-5199-4e5d-b513-36927645f71d"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("1919292b-c2e6-4abe-be91-12ffd50ff11b"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("16733a02-17bf-4bf7-9aaf-d5d2c6480c99"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8cc522eb-d103-42d7-9acb-816254174e7a"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7f16509f-248f-43aa-9124-808d1e800ba7"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4efccba7-2951-4b35-ac16-8d8033583809"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c3e0a80c-8e4c-42c7-af63-2e0c290b222a"),
                            RowIdentifier = "C",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a3bd8cd8-5243-4904-9d72-472212842306"),
                            RowIdentifier = "C",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f619ee44-6302-49bd-b359-0f68f23afef5"),
                            RowIdentifier = "C",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("543f30b6-a9f7-439b-8d39-c6c5e15d13ad"),
                            RowIdentifier = "C",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5dee5220-4a88-4f1f-88a9-815a4505f2da"),
                            RowIdentifier = "C",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("765adbbe-dc32-4535-b32a-eb09edee7a32"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("82e367df-d860-48fb-8815-a354563c7641"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("322c456b-fba3-402d-94eb-2c76329afbcc"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("354d8bbb-7861-4dff-b771-6ac209f65e70"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("cb8815b4-4681-4de0-b2fb-941df2ebbdbd"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3e59f611-bb49-4e31-878b-ee10fcbf6665"),
                            RowIdentifier = "D",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5894efdb-95fa-44a5-90c2-21e6965af3c6"),
                            RowIdentifier = "D",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7d850116-4fdd-4793-bae1-c6673bdd86e4"),
                            RowIdentifier = "D",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ce50b42a-bea0-4692-8716-8b840a94d0f0"),
                            RowIdentifier = "D",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ffb7145d-b8b3-4aa2-819e-3698a2d09b0c"),
                            RowIdentifier = "D",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("24b1930a-aa2f-4595-818f-a20c35210290"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b259ada0-9b53-4e58-aa9d-8e88f258d925"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f7e6513d-954b-42ff-9657-649c4810f935"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b2be0159-4d7e-40ca-9f72-8ff38f7b6d58"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("feddee16-1131-4758-bf4c-7ff36486bb18"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("89edfe1f-9991-4aaa-b5e0-9ec231324de8"),
                            RowIdentifier = "E",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("897a7bca-35a9-473b-a076-f8f76883925a"),
                            RowIdentifier = "E",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("701277ae-5961-4116-8a03-e500dde84927"),
                            RowIdentifier = "E",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0d3bf94d-b824-400a-81e9-61e1fb5d3e57"),
                            RowIdentifier = "E",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("73d7c3af-eb36-4ef5-8906-918a1c68d622"),
                            RowIdentifier = "E",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Sectors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "VIP",
                            Price = 15000.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "General",
                            Price = 5000.00m
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@ticketflow.com",
                            Name = "Admin General",
                            PasswordHash = "$2a$12$eQQOCJVOpp0NS8MJ0C5c1Oo6gbsC58uD.j6wZE9Z6xnzfMsRd1H6G",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ale@ticketflow.com",
                            Name = "Alejandro",
                            PasswordHash = "$2a$12$WQUmKUbkI6C6a2e5nDxfvO42I5fVVOnVlE1JnYAWXGP914Cs4RMPC",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 3,
                            Email = "agus@ticketflow.com",
                            Name = "Agustin",
                            PasswordHash = "$2a$12$aJGDFO5wFcTycwlLZ1XfFepllyAhVEawY/pOPvmZKnUcf/BEHlDqy",
                            Role = "Client"
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketFlow.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Seat", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Sector", "Sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Event", "Event")
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Event", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
