// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketFlow.Infrastructure.Persistence;

#nullable disable

namespace TicketFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419190713_AddReservationUserAndAudit")]
    partial class AddReservationUserAndAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 10, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Concierto de Rock Universitario",
                            Status = "Active",
                            Venue = "Estadio UNAJ"
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b777fbe-9c40-4220-ad2f-6b765e2f7f67"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9ff9b21f-5456-418b-bc0c-9147cda5d8f4"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d8654778-d833-426a-83de-0dd9f3e234b8"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("010d10e4-388a-453f-92c1-31dafed7fbad"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8e664ca3-404b-4070-b1b2-a91a38982632"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7db1d41f-f0a7-4a38-96ed-e355bb511fed"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("27ad3a7a-2c64-4280-b01e-fd33f20d146b"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0286176a-0494-4399-aaa0-ee8a9efa356f"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d159f490-b626-4165-8f42-00a711e9f8e9"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4c4c78e5-8ba9-407e-a619-94a858dddaae"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("65330b81-c1d4-4fdc-b7a4-1be7dea182bc"),
                            RowIdentifier = "A",
                            SeatNumber = 11,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("dc46415e-3f4c-4061-af5d-a22e561f9cb1"),
                            RowIdentifier = "A",
                            SeatNumber = 12,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b721393f-aeb7-4079-a95e-a6569d5f6252"),
                            RowIdentifier = "A",
                            SeatNumber = 13,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("68231cf2-2024-4e84-8f44-7ccd4a1480cd"),
                            RowIdentifier = "A",
                            SeatNumber = 14,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7aa86c02-6c72-435c-adbb-2bcd9849f380"),
                            RowIdentifier = "A",
                            SeatNumber = 15,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6b7bf540-f975-4059-9742-ca4bfa0670a3"),
                            RowIdentifier = "A",
                            SeatNumber = 16,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("282063f8-c420-4322-8b59-dc1ee3d1c2b0"),
                            RowIdentifier = "A",
                            SeatNumber = 17,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("96cec133-6b01-46c4-8441-d98595617492"),
                            RowIdentifier = "A",
                            SeatNumber = 18,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("be56f09a-d421-42ce-a2bd-efc2a546c116"),
                            RowIdentifier = "A",
                            SeatNumber = 19,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("766aafe8-b093-4e58-b509-3c49f86905ac"),
                            RowIdentifier = "A",
                            SeatNumber = 20,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("973ac3f5-c9c3-4b18-a8d1-398f860c7cee"),
                            RowIdentifier = "A",
                            SeatNumber = 21,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("62c013a2-3608-450f-8a53-81ceaa5a114e"),
                            RowIdentifier = "A",
                            SeatNumber = 22,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8c1b3f2c-d026-4b87-85ed-817bef53da9e"),
                            RowIdentifier = "A",
                            SeatNumber = 23,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("988782d8-2d28-4270-9acd-c1b6b914e2a3"),
                            RowIdentifier = "A",
                            SeatNumber = 24,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("da11155d-d8c4-4668-b21f-49a76fcbdcda"),
                            RowIdentifier = "A",
                            SeatNumber = 25,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a8b6238f-f3c9-4664-a4a9-4475dfc0eac0"),
                            RowIdentifier = "A",
                            SeatNumber = 26,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("29eb86d7-e25e-4c94-b420-63664b149dc9"),
                            RowIdentifier = "A",
                            SeatNumber = 27,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("37731e90-ca6b-4357-8e80-2797e3ca02d2"),
                            RowIdentifier = "A",
                            SeatNumber = 28,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a9029da2-1391-4063-bd18-6ddda46810e8"),
                            RowIdentifier = "A",
                            SeatNumber = 29,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("637b2930-5ac6-4bc7-80ed-2436875129a1"),
                            RowIdentifier = "A",
                            SeatNumber = 30,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7a91a07e-6213-463f-9dc1-9b7b6d1d7bbe"),
                            RowIdentifier = "A",
                            SeatNumber = 31,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c501c2b4-9a8e-4eed-8989-8dc4c8d478c7"),
                            RowIdentifier = "A",
                            SeatNumber = 32,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("940c684a-cfa2-4952-b71f-fdfeb3ad623f"),
                            RowIdentifier = "A",
                            SeatNumber = 33,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a8ccb309-a7c9-4266-a51c-6f51e5b4914d"),
                            RowIdentifier = "A",
                            SeatNumber = 34,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("28efaada-362e-4643-8912-7fbe753920b7"),
                            RowIdentifier = "A",
                            SeatNumber = 35,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("35d4c8bc-9086-400b-91b6-f33a98080d7d"),
                            RowIdentifier = "A",
                            SeatNumber = 36,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c631a2f8-8f67-4a95-bc34-826b730df7e6"),
                            RowIdentifier = "A",
                            SeatNumber = 37,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("74e3af23-7b79-4268-bb34-b024cf3e4989"),
                            RowIdentifier = "A",
                            SeatNumber = 38,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("24af3176-c767-4a9d-9bbd-b3e9082f025d"),
                            RowIdentifier = "A",
                            SeatNumber = 39,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5047adeb-67b8-495f-8393-0d2952c5d254"),
                            RowIdentifier = "A",
                            SeatNumber = 40,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3580391d-c711-4b3a-a533-fdc59cb67a0d"),
                            RowIdentifier = "A",
                            SeatNumber = 41,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d44bd392-f5c9-4f49-a68e-71e4b1a8e126"),
                            RowIdentifier = "A",
                            SeatNumber = 42,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3f0a0aaf-1bdc-4417-9dac-aee3adeaace7"),
                            RowIdentifier = "A",
                            SeatNumber = 43,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6b3ba1a8-1bc8-4e91-b933-19a7d4da350b"),
                            RowIdentifier = "A",
                            SeatNumber = 44,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9c6529ba-b14f-41d4-81d8-7c92079c0c3b"),
                            RowIdentifier = "A",
                            SeatNumber = 45,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5618733c-f3a5-4951-9fe5-ae9df142afd1"),
                            RowIdentifier = "A",
                            SeatNumber = 46,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c117ef32-bf93-497f-a377-2fa9334f2450"),
                            RowIdentifier = "A",
                            SeatNumber = 47,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e6e6f2f3-3f58-4bb8-9ca9-0b3914d9a8eb"),
                            RowIdentifier = "A",
                            SeatNumber = 48,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5b76252a-40fa-4122-84ae-ad814195d727"),
                            RowIdentifier = "A",
                            SeatNumber = 49,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f4c8d7af-a642-4a14-8c88-a7d7771485d5"),
                            RowIdentifier = "A",
                            SeatNumber = 50,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11f9b195-c3c1-48ab-b880-f319102102bd"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3638e0af-2692-49b4-9943-16e6971a7523"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c009c0ac-aa80-4c98-9928-b6cb888ee07c"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7960ed4d-b942-4704-8140-e0724a5e5b35"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("167ce08c-c615-49b5-9345-752293401c2e"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a882619d-1260-4208-b61d-d06722f59e6a"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("bd9d6b9a-c590-4bd1-b56d-f16cc8cebe7f"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("23ec113b-c338-4b5e-b416-beae1b192838"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("740fd539-1060-4aaa-820b-1457893de79b"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("52e6fe31-d2bf-4eca-a52b-2609193b9b5d"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8e435141-bf59-4f3b-a516-9d7addc6b5f2"),
                            RowIdentifier = "B",
                            SeatNumber = 11,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a0b4b86f-59eb-421d-b5e0-32b2150f53e1"),
                            RowIdentifier = "B",
                            SeatNumber = 12,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("88f472a1-e04f-44e0-8883-863d6d398825"),
                            RowIdentifier = "B",
                            SeatNumber = 13,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9c421316-7893-4780-ba28-322a8af7566f"),
                            RowIdentifier = "B",
                            SeatNumber = 14,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("555ae8bf-b374-4496-8cff-fede2a1444c7"),
                            RowIdentifier = "B",
                            SeatNumber = 15,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("98d973d9-4e6a-416a-90a9-76b257f64e0b"),
                            RowIdentifier = "B",
                            SeatNumber = 16,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("29df7c9e-80ec-4ba1-a0d4-1e7b92d4d951"),
                            RowIdentifier = "B",
                            SeatNumber = 17,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c5863bfc-6bb8-4462-be1b-29a8a0b5ee95"),
                            RowIdentifier = "B",
                            SeatNumber = 18,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00b5e1b2-2d71-405e-824d-d7d090db1543"),
                            RowIdentifier = "B",
                            SeatNumber = 19,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("046aac8a-46a0-4cc8-9358-56d90de5f015"),
                            RowIdentifier = "B",
                            SeatNumber = 20,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e5c7acbc-e658-415f-865f-9c529ed95539"),
                            RowIdentifier = "B",
                            SeatNumber = 21,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("71b8a684-9004-4977-bd2c-254158e8f2a3"),
                            RowIdentifier = "B",
                            SeatNumber = 22,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4c7255b1-495d-43db-ba53-f5c049af73a5"),
                            RowIdentifier = "B",
                            SeatNumber = 23,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("28bc76a8-5f4c-400a-8f0e-80a00c5a5d45"),
                            RowIdentifier = "B",
                            SeatNumber = 24,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("1c65014b-4e07-4146-be94-419ceedaa2ff"),
                            RowIdentifier = "B",
                            SeatNumber = 25,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("15223da0-71fd-48a1-9461-dfaac8dc4cfd"),
                            RowIdentifier = "B",
                            SeatNumber = 26,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8ee7722d-bc22-4e46-aff2-97a8929a8126"),
                            RowIdentifier = "B",
                            SeatNumber = 27,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c7e99cee-5936-47b1-8002-41967cdfd555"),
                            RowIdentifier = "B",
                            SeatNumber = 28,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("886ccb64-2bdb-47b4-885d-d6c724fe6d7a"),
                            RowIdentifier = "B",
                            SeatNumber = 29,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("367b2e33-6338-4889-99d3-e010d12ec493"),
                            RowIdentifier = "B",
                            SeatNumber = 30,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ff6af541-3da6-48a7-bd50-328df4735077"),
                            RowIdentifier = "B",
                            SeatNumber = 31,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("186404f9-ac5c-46cb-8a14-6be6200182b7"),
                            RowIdentifier = "B",
                            SeatNumber = 32,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c6cd4c37-5a27-42bf-af8c-290f067a46d7"),
                            RowIdentifier = "B",
                            SeatNumber = 33,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9bd0e2ea-d307-4f7a-b346-ed802534f7b1"),
                            RowIdentifier = "B",
                            SeatNumber = 34,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("48009b98-3a10-403e-b59c-aaac7bf91a5b"),
                            RowIdentifier = "B",
                            SeatNumber = 35,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9aab7bab-5939-4789-8195-0439ec6bc138"),
                            RowIdentifier = "B",
                            SeatNumber = 36,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("93576ab2-ff5b-4b6e-a867-5ca6ed6068a7"),
                            RowIdentifier = "B",
                            SeatNumber = 37,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b74fb0ce-e71c-44cb-a5b8-ec6aa1ac8f60"),
                            RowIdentifier = "B",
                            SeatNumber = 38,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("84c8d2c6-e2e6-4ed9-88fc-d8d0b3addb70"),
                            RowIdentifier = "B",
                            SeatNumber = 39,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f0754b9c-5f0c-4d92-904a-ca0770b9d7de"),
                            RowIdentifier = "B",
                            SeatNumber = 40,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d775e9c6-bbf8-4042-9dcf-3db882398d8e"),
                            RowIdentifier = "B",
                            SeatNumber = 41,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c7f028ac-6ac5-4fde-92bc-c6248c937a59"),
                            RowIdentifier = "B",
                            SeatNumber = 42,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("96846c2b-d5f8-4eca-a01a-3444ed1b1ab0"),
                            RowIdentifier = "B",
                            SeatNumber = 43,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9ff83104-6326-4832-b30c-e69f3dca8d19"),
                            RowIdentifier = "B",
                            SeatNumber = 44,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("89453466-8da4-4330-9392-88c6416d9886"),
                            RowIdentifier = "B",
                            SeatNumber = 45,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a6a0ffcc-fa67-412c-ab2b-aaece3e430f1"),
                            RowIdentifier = "B",
                            SeatNumber = 46,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("03b82c21-a3b0-459b-80b5-1bb7da48bc96"),
                            RowIdentifier = "B",
                            SeatNumber = 47,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("91882da0-6fa4-4b72-b96d-56f95777dd8f"),
                            RowIdentifier = "B",
                            SeatNumber = 48,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9678e4d2-b08a-4e12-9db4-1cff8f1b2ad7"),
                            RowIdentifier = "B",
                            SeatNumber = 49,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("15a9a2cc-72a2-44de-984f-9eff0760d008"),
                            RowIdentifier = "B",
                            SeatNumber = 50,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Sectors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "VIP",
                            Price = 15000.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "General",
                            Price = 5000.00m
                        });
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketFlow.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Seat", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Sector", null)
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.HasOne("TicketFlow.Domain.Entities.Event", null)
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Event", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
